basePath: /
consumes:
- 'application/json '
- 'Products:'
- application/json
info:
  description: 'Documentation for Product API '
  title: 'of Product API '
  version: 1.0.0
paths: {}
schemes:
- http
swagger: "2.0"
